<#
.SYNOPSIS
  Registers the Cursor Remote daemon to start automatically on this machine.

.DESCRIPTION
  Creates a Scheduled Task that launches the daemon at logon and restarts it if
  it stops. A Scheduled Task rather than a Windows service on purpose: the
  agents it runs need your user session, your PATH, your git credentials, and
  your Cursor login. A LocalSystem service has none of those.

  Run from the repo root (works on the Windows PowerShell that ships with the OS,
  so there is nothing to install first):
    powershell -ExecutionPolicy Bypass -File apps\daemon\scripts\install-service.ps1

.PARAMETER Remove
  Unregister the task instead of creating it.

.PARAMETER KeepAwake
  Also stop the machine sleeping while plugged in, so tool calls can still run
  when you are away from it. This is a machine-wide power setting.
#>
[CmdletBinding()]
param(
    [switch]$Remove,
    [switch]$KeepAwake
)

$ErrorActionPreference = "Stop"
$taskName = "CursorRemoteDaemon"

if ($Remove) {
    if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
        Write-Host "Removed the $taskName task."
    }
    else {
        Write-Host "No $taskName task was registered."
    }
    return
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..")).Path
$entryPoint = Join-Path $repoRoot "apps\daemon\dist\index.js"

if (-not (Test-Path $entryPoint)) {
    throw "$entryPoint is missing. Run 'npm run build' in $repoRoot first."
}

$nodeCommand = Get-Command node -ErrorAction SilentlyContinue
$node = if ($nodeCommand) { $nodeCommand.Source } else { $null }
if (-not $node) {
    throw "node is not on PATH. Install Node 22.13 or later."
}

$config = Join-Path $env:USERPROFILE ".cursorremote\config.json"
if (-not (Test-Path $config)) {
    Write-Warning "$config does not exist yet. The daemon writes a starter one on first run; edit its projects list afterwards."
}

# Run through a hidden PowerShell so there is no console window sitting in the
# taskbar, and so stdout and stderr land in a file. A background daemon whose
# output goes nowhere fails invisibly, which is the one thing we cannot afford
# here: you would just see an app that never reconnects.
$logDir = Join-Path $env:USERPROFILE ".cursorremote\logs"
New-Item -ItemType Directory -Path $logDir -Force | Out-Null
$logPath = Join-Path $logDir "daemon.log"

$launcher = Join-Path $logDir "run-daemon.ps1"
@"
# Generated by install-service.ps1. Edits here are overwritten on reinstall.
`$log = '$logPath'
if ((Test-Path `$log) -and (Get-Item `$log).Length -gt 10MB) {
    Move-Item `$log "`$log.old" -Force
}
Set-Location '$repoRoot'
& '$node' '$entryPoint' *>> `$log
"@ | Set-Content -Path $launcher -Encoding UTF8

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$launcher`"" `
    -WorkingDirectory $repoRoot
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

# Defaults that matter: no battery-based throttling, no time limit, and a
# restart if the daemon ever falls over while you are away from the machine.
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -DontStopOnIdleEnd `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -StartWhenAvailable

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
}

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Description "Runs the Cursor Remote daemon so other devices can reach this machine's agents." `
    -RunLevel Limited | Out-Null

Write-Host "Registered $taskName. It starts at your next logon."
Write-Host "Start it now with:  Start-ScheduledTask -TaskName $taskName"
Write-Host "Logs (including the URL and token):  $logPath"

if ($KeepAwake) {
    # Only the plugged-in profile: letting a laptop on battery stay awake in a
    # bag is a worse outcome than a missed agent run.
    powercfg /change standby-timeout-ac 0
    powercfg /change hibernate-timeout-ac 0
    Write-Host "This machine will no longer sleep while plugged in."
}
